### ISSUE TITLE
intro_to_ruby_hashes_lab_spec.rb

### ISSUE THREAD

**Issue by Richard-Frost** [learn-co-curriculum/ruby-intro-to-hashes-lab#26]
line 148:

```
`mortgage_value` => '$800'
```

should be 

'mortgage_value'

not a big deal but i was copying and pasting and it caused a moment of issues until i saw the mistake.

**Comment by AnnJohn** [comment]
Hi @Richard-Frost not sure that I see the issue. Line 148 is blank and the one above it is an it/ do statement which shouldn't affect anything. Could you please share a screenshot or clarify a little bit more? Thanks!

**Comment by AnnJohn** [comment]
closing
