### ISSUE TITLE
monopoly with second tier

### ISSUE THREAD

**Issue by psmathers** [learn-co-curriculum/ruby-intro-to-hashes-lab#27]
In the r_spec test, the build is in the wrong order. It should be :rent_in_dollars, then :names.

**Comment by AnnJohn** [comment]
thanks @psmathers for bringing this up. We'll change the order as soon as we can get to it.

**Comment by AnnJohn** [comment]
hi @psmathers the solution should be :names and then :rent_in_dollars so the order of the build in the spec test should be correct.
