### ISSUE TITLE
missing word "key" in description for spec test #4, will fix in my submit

### ISSUE THREAD

**Issue by molotov2k** [learn-co-curriculum/ruby-intro-to-hashes-lab#28]
building a multidimensional monopoly hash
  adding a key-value pair to the top level of the monopoly hash
    #monopoly
      add a key value pair to the monopoly hash. The **KEY** should be :railroads and the value should be an empty hash (FAILED - 1)

**Comment by AnnJohn** [comment]
thanks @molotov2k we'll look at this soon!

**Comment by vicfriedman** [comment]
thanks!
