### ISSUE TITLE
There's an error with the way that the final monopoly hash is shown in the README.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/ruby-intro-to-hashes-lab#31]
Hello. If you look at the monopoly hash in the README and examine monopoly[:railroads], its values (which themselves are keys) are in this order: 

:pieces, :rent_in_dollars, :names.

However, the tests specify that the values of monopoly[:railroads] are supposed to be in this exact order:

:pieces, :names, :rent_in_dollars.

I have attached a screenshot for clarity. Thank you for looking into this.

Sdcrouse

![building nested hashes screenshot](https://user-images.githubusercontent.com/38870640/44379316-32536a80-a4ba-11e8-87ae-0e66a3d86f5e.gif)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Sdcrouse.

We have updated the tests and solution in this lesson to match the readme and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
